[package]
name = "vm"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@rymdkoloni.se>"]
edition = "2018"

[dependencies]
wasmi = "*"
parity-wasm = "0.31"
wabt = "*"
signatory = "*"
signatory-dalek = "*"
blake2-rfc = "0.2"
ethereum-types = "0.4"
failure = "*"