[package]
name = "rusk-vm"
version = "0.1.1"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
signatory = "0.18"
signatory-dalek = "0.18"
blake2-rfc = "0.2"
failure = "0.1"
serde = "1.0"
kelvin = "0.9"
kelvin-radix = "0.5"
fermion = "0.2"

phoenix = { path = "../phoenix" }
phoenix-abi = { path = "../phoenix-abi" }
dusk-abi = { path = "./dusk-abi" }
lazy_static = "1.4"
parking_lot = "0.10"

[dev-dependencies]
tempfile = "*"
criterion = "0.3"

default_account = { path = "tests/contracts/default_account/wasm" }
factorial = { path = "tests/contracts/factorial/wasm" }
transfer = { path = "tests/contracts/transfer/wasm" }

[[bench]]
sample_size = 10
name = "factorial"
harness = false