[package]
name = "vm"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = "0.5"
parity-wasm = "0.39"
signatory = "0.12"
signatory-dalek = "0.12"
blake2-rfc = "0.2"
failure = "0.1"
dusk-abi = { path = "./dusk-abi" }
serde = "1.0"

default_account = { path = "contracts/default_account" }

[dev-dependencies]
factorial = { path = "contracts/factorial" }
