[package]
name = "vm"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = { path = "../wasmi" }
parity-wasm = "0.39"
wabt = "*"
signatory = "*"
signatory-dalek = "*"
blake2-rfc = "0.2"
failure = "*"
genesis = { path = "genesis" }
dusk-abi = { path = "./dusk-abi" }

[dev-dependencies]
default_account = { path = "contracts/default_account" }

