[package]
name = "rusk-vm"
version = "0.2.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
failure = "0.1"

dusk-abi = { path = "dusk-abi", version = "0.3" }
canonical = { version = "0.5" , features = ["host"] }
canonical_host = "0.5"
canonical_derive = "0.5"
dusk-kelvin-map = "0.2"

[dev-dependencies]

# test contracts
counter = { path = "tests/contracts/counter", features = ["host"] }
fibonacci = { path = "tests/contracts/fibonacci", features = ["host"] }
delegator = { path = "tests/contracts/delegator", features = ["host"] }

[[bench]]
name = "factorial"
harness = false