[package]
name = "rusk-vm"
version = "0.2.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
signatory = "0.18"
signatory-dalek = "0.18"
blake2-rfc = "0.2"
failure = "0.1"
kelvin = "0.12"
kelvin-radix = "0.8"
lazy_static = "1.4"
parking_lot = "0.10"
threshold_crypto_ce = "0.4"

dusk-abi = { git = "https://github.com/dusk-network/dusk-abi" }
dataview = { git = "https://github.com/dusk-network/dataview.git" }

[dev-dependencies]
tempfile = "*"
criterion = "0.3"
cake-rusk = { git = "https://github.com/dusk-network/cake-rusk" }

[[bench]]
name = "factorial"
harness = false
