[package]
name = "rusk-vm"
version = "0.5.1"
authors = [
  "Kristoffer Ström <kristoffer@dusk.network>",
  "zer0 <matteo@dusk.network>"
]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
failure = "0.1"

dusk-abi = "0.7"

canonical = { path = "../canonical/canon", default-features = false }
canonical_derive = { path = "../canonical/canon_derive" }
dusk-hamt = { path = "../dusk-hamt" }

# [dev-dependencies]
# dusk-bls12_381 = "0.6"
# dusk-bytes = "0.1"

# test contracts
counter = { path = "tests/contracts/counter", features = ["host"] }
fibonacci = { path = "tests/contracts/fibonacci", features = ["host"] }
delegator = { path = "tests/contracts/delegator", features = ["host"] }
stack = { path = "tests/contracts/stack", features = ["host"] }
block_height = { path = "tests/contracts/block_height", features = ["host"] }
self_snapshot = { path = "tests/contracts/self_snapshot", features = ["host"] }
host_fn = { path = "tests/contracts/host_fn", features = ["host"] }
tx_vec = { path = "tests/contracts/tx_vec", features = ["host"] }
dusk-poseidon = "0.18"

[[bench]]
name = "factorial"
harness = false

[workspace]

members = [
    "tests/contracts/*",
]

[patch.crates-io]
canonical = { path = "../canonical/canon" }
canonical_derive = { path = "../canonical/canon_derive" }
dusk-abi = { path = "../dusk-abi" }