[package]
name = "rusk-vm"
version = "0.3.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
failure = "0.1"

dusk-abi = { path = "dusk-abi", version = "0.3" }
canonical = { version = "0.5" , features = ["host"] }
canonical_host = "0.5"
canonical_derive = "0.5"
dusk-kelvin-map = "0.3"
dusk-plonk = "0.5"
rusk-profile = {git = "https://github.com/dusk-network/rusk/", branch = "master"}
transfer-circuits = {git = "https://github.com/dusk-network/rusk/", branch = "master"}
anyhow = {version = "1.0", optional = true}

poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.17.0"}
dusk-bls12_381 = "0.6"
dusk-bytes = "0.1"
bincode = "1.0"

[dev-dependencies]
rand = "0.7"
# test contracts
counter = { path = "tests/contracts/counter", features = ["host"] }
fibonacci = { path = "tests/contracts/fibonacci", features = ["host"] }
delegator = { path = "tests/contracts/delegator", features = ["host"] }
stack = { path = "tests/contracts/stack", features = ["host"] }
hash = { path = "tests/contracts/hash", features = ["host"] }
proof_verification = { path = "tests/contracts/proof_verification", features = ["host"] }

[[bench]]
name = "factorial"
harness = false

[features]
dummy_circ = ["anyhow"]
