[package]
name = "rusk-vm"
version = "0.2.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
blake2-rfc = "0.2"
failure = "0.1"
lazy_static = "1.4"
parking_lot = "0.10"

dusk-abi = { path = "dusk-abi" }
canonical = { version = "0.4" , features = ["host"] }
canonical_host = { version = "0.4" }
canonical_derive = { version = "0.4" }
dusk-kelvin-map = "0.2"

[dev-dependencies]
tempfile = "*"
criterion = "0.3"
cake-rusk = { git = "https://github.com/dusk-network/cake-rusk" }

# test contracts
counter = { path = "tests/contracts/counter", features = ["host"] }
fibonacci = { path = "tests/contracts/fibonacci", features = ["host"] }
delegator = { path = "tests/contracts/delegator", features = ["host"] }

[[bench]]
name = "factorial"
harness = false

[patch.crates-io]
canonical = { path = "../canonical/canon" }
canonical_host = { path = "../canonical/canon_host" }
canonical_derive = { path = "../canonical/canon_derive" }
