[package]
name = "vm"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
pwasm-utils = "0.12.0"
integer-sqrt = "0.1.2"
signatory = "0.12"
signatory-dalek = "0.12"
blake2-rfc = "0.2"
failure = "0.1"
dusk-abi = { path = "./dusk-abi" }
serde = "1.0"

default_account = { path = "contracts/default_account" }

[dev-dependencies]
factorial = { path = "contracts/factorial" }
add = { path = "contracts/add" }
