[package]
name = "test_contract"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@rymdkoloni.se>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[dependencies]
wasm-bindgen = "*"
blake2-rfc = "0.2.17"